@startuml
start

:Открыть главную страницу Subscribe.ru;
:Найти ссылку "Регистрация";
:Нажать "Регистрация";

if (Открылся регистрационный интерфейс?) then (Да)
  :Показать форму регистрации;
else (Нет)
  :Перенаправить пользователя\nв маршрут регистрации;
endif

:Пользователь находится\nв регистрационном потоке;
stop
@enduml
