@startuml
start

:Открыть главную страницу Subscribe.ru;
:Найти доступную кнопку "Подписаться";
:Нажать "Подписаться";

if (Пользователь авторизован?) then (Да)
  :Перейти к оформлению подписки;
else (Нет)
  :Открыть авторизацию\nили регистрацию;
endif

:Поток подписки запущен;
stop
@enduml
